name: base
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotlipy=0.7.0=py39h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.07.19=h06a4308_0
  - certifi=2022.6.15=py39h06a4308_0
  - cffi=1.15.1=py39h74dc2b5_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - conda=4.14.0=py39h06a4308_0
  - conda-package-handling=1.8.1=py39h7f8727e_0
  - cryptography=37.0.1=py39h9ce1e76_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cytoolz=0.11.0=py39h27cfd23_0
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.11.0=h70c0345_0
  - giflib=5.2.1=h7b6447c_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - idna=3.3=pyhd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9e=h7f8727e_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libdeflate=1.8=h7f8727e_5
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.4.0=hecacb30_0
  - libunistring=0.9.10=h27cfd23_0
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - lz4-c=1.9.3=h295c915_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - ncurses=6.3=h5eee18b_3
  - nettle=3.7.3=hbbd107a_1
  - numpy-base=1.23.1=py39ha15fc14_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1q=h7f8727e_0
  - pip=22.1.2=py39h06a4308_0
  - pycosat=0.6.3=py39h27cfd23_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.12=h12debd9_0
  - pytorch=1.12.1=py3.9_cuda11.3_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - readline=8.1.2=h7f8727e_1
  - requests=2.28.1=py39h06a4308_0
  - ruamel_yaml=0.15.100=py39h27cfd23_0
  - setuptools=63.4.1=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.39.2=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - toolz=0.11.2=pyhd3eb1b0_0
  - torchaudio=0.12.1=py39_cu113
  - tqdm=4.64.0=py39h06a4308_0
  - tzdata=2022a=hda174b7_0
  - urllib3=1.26.11=py39h06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.12=h7f8727e_2
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - absl-py==2.1.0
    - accelerate==0.28.0
    - aiosignal==1.3.1
    - ale-py==0.7.5
    - annotated-types==0.6.0
    - anyio==4.2.0
    - astunparse==1.6.3
    - attrs==22.2.0
    - beautifulsoup4==4.11.1
    - boto3==1.28.85
    - botocore==1.31.85
    - cachetools==5.3.3
    - click==8.1.3
    - cloudpickle==2.2.0
    - contourpy==1.0.5
    - cycler==0.11.0
    - cython==0.29.32
    - distro==1.9.0
    - dm-tree==0.1.8
    - docker-pycreds==0.4.0
    - exceptiongroup==1.1.0
    - farama-notifications==0.0.4
    - filelock==3.8.0
    - flatbuffers==23.5.26
    - fonttools==4.37.2
    - frozenlist==1.4.1
    - fsspec==2024.2.0
    - gast==0.4.0
    - gdown==4.5.1
    - gitdb==4.0.9
    - gitpython==3.1.27
    - google-ai-generativelanguage==0.6.2
    - google-api-core==2.18.0
    - google-api-python-client==2.127.0
    - google-auth==2.28.1
    - google-auth-httplib2==0.2.0
    - google-auth-oauthlib==1.2.0
    - google-generativeai==0.5.2
    - google-pasta==0.2.0
    - googleapis-common-protos==1.63.0
    - grpcio==1.62.2
    - grpcio-status==1.62.2
    - gym==0.23.1
    - gym-notices==0.0.8
    - gymnasium==0.28.1
    - h11==0.14.0
    - h5py==3.10.0
    - httpcore==1.0.2
    - httplib2==0.22.0
    - httpx==0.26.0
    - huggingface-hub==0.21.4
    - imageio==2.33.1
    - importlib-metadata==4.12.0
    - importlib-resources==6.1.1
    - iniconfig==1.1.1
    - jax-jumpy==1.0.0
    - jinja2==3.1.3
    - jmespath==1.0.1
    - jsonschema==4.21.1
    - jsonschema-specifications==2023.12.1
    - keras==2.15.0
    - kiwisolver==1.4.4
    - lazy-loader==0.3
    - libclang==16.0.6
    - lz4==4.3.3
    - markdown==3.5.2
    - markdown-it-py==3.0.0
    - markupsafe==2.1.5
    - matplotlib==3.6.0
    - mdurl==0.1.2
    - ml-dtypes==0.2.0
    - msgpack==1.0.7
    - networkx==3.2.1
    - nose==1.3.7
    - numpy==1.26.4
    - oauthlib==3.2.2
    - openai==1.11.1
    - opt-einsum==3.3.0
    - pandas==1.4.4
    - pathtools==0.1.2
    - pillow==9.2.0
    - pluggy==1.0.0
    - promise==2.3
    - proto-plus==1.23.0
    - protobuf==4.25.3
    - psutil==5.9.2
    - pyarrow==15.0.0
    - pyasn1==0.5.1
    - pyasn1-modules==0.3.0
    - pybaba==0.1
    - pydantic==2.6.1
    - pydantic-core==2.16.2
    - pygame==2.5.2
    - pyrvo2==0.0.0
    - pytest==7.2.0
    - python-dateutil==2.8.2
    - pytz==2022.2.1
    - pyyaml==6.0
    - ray==2.9.2
    - referencing==0.33.0
    - regex==2023.12.25
    - replicate==0.25.2
    - requests-oauthlib==1.3.1
    - rich==13.7.0
    - rpds-py==0.17.1
    - rsa==4.9
    - s3transfer==0.7.0
    - safetensors==0.4.2
    - scikit-image==0.22.0
    - scipy==1.9.1
    - seaborn==0.12.0
    - sentry-sdk==1.9.8
    - setproctitle==1.3.2
    - shortuuid==1.0.9
    - smmap==5.0.0
    - sniffio==1.3.0
    - soupsieve==2.3.2.post1
    - tensorboard==2.15.2
    - tensorboard-data-server==0.7.2
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.6.2.2
    - tensorflow==2.15.0.post1
    - tensorflow-estimator==2.15.0
    - tensorflow-io-gcs-filesystem==0.36.0
    - tensorflow-probability==0.23.0
    - termcolor==2.4.0
    - tifffile==2024.1.30
    - tiktoken==0.6.0
    - tokenizers==0.15.2
    - tomli==2.0.1
    - torch==1.12.1
    - torchvision==0.13.1
    - transformers==4.38.2
    - typer==0.9.0
    - typing-extensions==4.9.0
    - uritemplate==4.1.1
    - wandb==0.13.3
    - werkzeug==3.0.1
    - wrapt==1.14.1
    - zipp==3.8.1
